filter:
  excluded_paths:
    - 'vendor/*'
tools:
  php_analyzer:
    enabled: true
    extensions:
      - php
    filter:
      excluded_paths:
        - 'vendor/*'
  external_code_coverage:
    enabled: true
    filter:
      paths:
        - 'lib/*'
  php_pdepend:
    enabled: true
    configuration_file: null
    suffixes:
      - php
    excluded_dirs: {  }
    filter:
      excluded_paths:
        - 'vendor/*'
  php_hhvm:
    enabled: true
  php_sim:
    enabled: true
    min_mass: 16
    filter:
      excluded_paths:
        - 'vendor/*'
        - 'example/*'
        - 'test/*'
      paths: {  }
  php_changetracking:
    enabled: true
    bug_patterns:
      - '\bfix(?:es|ed)?\b'
    feature_patterns:
      - '\badd(?:s|ed)?\b'
      - '\bimplement(?:s|ed)?\b'
    filter:
      excluded_paths:
        - 'vendor/*'
      paths: {  }
before_commands: { }
after_commands: { }
artifacts: { }
build_failure_conditions: { }