before_commands:
  - composer install

filter:
  paths: ["lib/*", "test/*"]

tools:
  external_code_coverage:
    enabled: true
    filter:
      paths: ["lib/*"]
  php_code_sniffer:
    enabled: true
    config:
      standard: PSR2
  php_loc:
    enabled: true
    excluded_dirs: ["coverage", "example", "test", "vendor"]
  php_cpd:
    enabled: true
    filter:
      paths: ["lib/*"]
  php_cs_fixer:
    enabled: true
    config:
      level: all
  php_pdepend:
    enabled: true
    excluded_dirs: ["coverage", "example", "test", "vendor"]
  php_analyzer:
    enabled: true
    filter:
      paths: ["lib/*"]
  php_hhvm:
    enabled: true
  php_mess_detector:
    enabled: true
  php_sim:
    enabled: true
  php_changetracking:
    enabled: true
